# Generated by Django 5.2.2 on 2025-06-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0003_create_initial_roles_and_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
