# Generated by Django 5.0.2 on 2025-06-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0005_update_roles_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
